name: Deploy Lambda Function

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Set up virtual enviroment
      run: |
        python -m venv env
        source env/bin/activate
        
    - name: Install dependencies
      run: |
        source env/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: auto
      run: |
        pip install autopep8
        autopep8 --in-place --aggressive --aggressive app.py
        
    - name: Flake8
      run: |
        pip install flake8
        flake8 app.py
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
    
    - name: cli
      run: |
          aws s3 ls
